const manifest = require("./topogram-generator.json");

function entitiesFromGraph(graph) { return Object.values(graph.statements || {}).filter((statement) => statement.kind === "entity"); }
function sqlType(field) { const type = String(field.type || field.scalar || "text"); if (type === "uuid") return "TEXT"; if (type === "datetime") return "TEXT"; if (type === "integer") return "INTEGER"; if (type === "number") return "REAL"; if (type === "boolean") return "INTEGER"; return "TEXT"; }
function tableName(entity) { return String(entity.table || entity.name || entity.id || "resource").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "resource"; }
function renderSql(graph) { const entities = entitiesFromGraph(graph); const blocks = entities.map((entity) => { const fields = entity.fields || []; const cols = fields.map((field) => `  ${field.name} ${sqlType(field)}${field.required ? " NOT NULL" : ""}`); return `CREATE TABLE IF NOT EXISTS ${tableName(entity)} (\n${cols.join(",\n")}\n);`; }); return (blocks.join("\n\n") || "CREATE TABLE IF NOT EXISTS topogram_resource (\n  id TEXT NOT NULL,\n  name TEXT NOT NULL\n);") + "\n"; }
function renderPrisma(graph) { const entities = entitiesFromGraph(graph); return entities.map((entity) => { const fields = (entity.fields || []).map((field) => `  ${field.name} String${field.required ? "" : "?"}`); return `model ${String(entity.id || "Resource").replace(/[^A-Za-z0-9]/g, "_")} {\n${fields.join("\n")}\n}`; }).join("\n\n") + "\n"; }
function generate(context) { const sql = renderSql(context.graph || {}); const files = { "schema.sql": sql, "migrations/0001_init.sql": sql, "prisma/schema.prisma": renderPrisma(context.graph || {}), "package.json": JSON.stringify({ private: true, type: "module", scripts: { check: "node ./scripts/check.mjs", migrate: "node ./scripts/migrate.mjs" } }, null, 2) + "\n", "scripts/check.mjs": "import fs from 'node:fs'; if (!fs.existsSync('./schema.sql')) throw new Error('missing schema.sql'); console.log('Checked database lifecycle bundle.');\n", "scripts/migrate.mjs": "console.log('Apply migrations/0001_init.sql with your database migration runner.');\n" };  return { files, artifacts: { generator: manifest.id, projection: context.projection && context.projection.id }, diagnostics: [] }; }
module.exports = { manifest, generate };
